"""init

Revision ID: b519a33e577b
Revises: 
Create Date: 2026-03-12 01:48:09.010463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b519a33e577b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companies_house_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_sector', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('opencorporates_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_companies_house_id'), 'companies', ['companies_house_id'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('national_energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('energy_type', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('energy_consumption', sa.Float(), nullable=False),
    sa.Column('co2_emission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_energy_country'), 'national_energy', ['country'], unique=False)
    op.create_index(op.f('ix_national_energy_id'), 'national_energy', ['id'], unique=False)
    op.create_index(op.f('ix_national_energy_year'), 'national_energy', ['year'], unique=False)
    op.create_table('regional_emissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_authority', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('industry_total', sa.Float(), nullable=False),
    sa.Column('commercial_total', sa.Float(), nullable=False),
    sa.Column('public_sector_total', sa.Float(), nullable=False),
    sa.Column('domestic_total', sa.Float(), nullable=False),
    sa.Column('transport_total', sa.Float(), nullable=False),
    sa.Column('agriculture_total', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_emissions_id'), 'regional_emissions', ['id'], unique=False)
    op.create_index(op.f('ix_regional_emissions_local_authority'), 'regional_emissions', ['local_authority'], unique=False)
    op.create_index(op.f('ix_regional_emissions_year'), 'regional_emissions', ['year'], unique=False)
    op.create_table('environmental_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('energy_consumption_mwh', sa.Float(), nullable=False),
    sa.Column('carbon_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('water_usage_m3', sa.Float(), nullable=True),
    sa.Column('waste_generated_tonnes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reporting_year', name='uq_company_year')
    )
    op.create_index(op.f('ix_environmental_metrics_id'), 'environmental_metrics', ['id'], unique=False)
    op.create_table('loan_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('applied_rate', sa.Float(), nullable=False),
    sa.Column('esg_score', sa.Float(), nullable=False),
    sa.Column('estimated_carbon_savings', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('simulation_parameters', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_simulations_id'), 'loan_simulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_simulations_id'), table_name='loan_simulations')
    op.drop_table('loan_simulations')
    op.drop_index(op.f('ix_environmental_metrics_id'), table_name='environmental_metrics')
    op.drop_table('environmental_metrics')
    op.drop_index(op.f('ix_regional_emissions_year'), table_name='regional_emissions')
    op.drop_index(op.f('ix_regional_emissions_local_authority'), table_name='regional_emissions')
    op.drop_index(op.f('ix_regional_emissions_id'), table_name='regional_emissions')
    op.drop_table('regional_emissions')
    op.drop_index(op.f('ix_national_energy_year'), table_name='national_energy')
    op.drop_index(op.f('ix_national_energy_id'), table_name='national_energy')
    op.drop_index(op.f('ix_national_energy_country'), table_name='national_energy')
    op.drop_table('national_energy')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_companies_house_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
