"""Create companies table

Revision ID: 6df59d73aea3
Revises:
Create Date: 2026-02-19 14:19:28.387601

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6df59d73aea3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companies_house_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_sector', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_companies_house_id'), 'companies', ['companies_house_id'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('environmental_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('energy_consumption_mwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbon_emissions_tco2e', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('water_usage_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('waste_generated_tonnes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'reporting_year', name='uq_company_year')
    )
    op.create_index(op.f('ix_environmental_metrics_id'), 'environmental_metrics', ['id'], unique=False)
    op.create_table('loan_simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount_gbp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_term_years', sa.Integer(), nullable=False),
    sa.Column('base_interest_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('green_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('green_discount', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('simulated_final_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('estimated_co2_savings_tco2e', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('simulation_parameters', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_simulations_id'), 'loan_simulations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_simulations_id'), table_name='loan_simulations')
    op.drop_table('loan_simulations')
    op.drop_index(op.f('ix_environmental_metrics_id'), table_name='environmental_metrics')
    op.drop_table('environmental_metrics')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_companies_house_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
